spring:
  application:
    name: container-core-apimanager

  datasource:
    url: jdbc:postgresql://localhost:5437/solicitud_pases_db
    driver-class-name: org.postgresql.Driver
    username: root
    password: em5DoRNmnyW9QqihdLDTHy4juIti6x

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8081

encryption:
  key: ${ENCRYPTION_KEY:YOURKEY}